### ISSUE TITLE
Docs about "time to restore" calculation not consistent in METRICS.md file

### ISSUE THREAD

**Issue by philipdalen** [GoogleCloudPlatform/fourkeys#119]
In METRICS.md it says "the median amount of time between the deployment which caused the failure" but in the slq query it uses "time_created" which is the time the incident was created. Please see below screenshot

![image](https://user-images.githubusercontent.com/12196246/118778674-9fbea080-b88a-11eb-86e6-f35b792f3950.png)

**Comment by Shabirmean** [comment]
Hello @philipdalen 

Thank you for raising this. The part you have highlighted is inside the `TIMESTAMP_DIFF()` which is calculating the time taken to restore from an incident _(in hours)_ by taking the difference between the `time_created` and `time_resolved`. Then uses the `PERCENTILE_CONT` to get the 50th (0.5 or median) percentile.

Let us know if that clarifies your question.

**Comment by philipdalen** [comment]
@Shabirmean not really :) Please have a look at the below drawing. Based on SQL query registered in the issue description time is measured as indicated by arrow no. 2 and not arrow no. 1.  I interpreted you're definition of "Time to Restore Service" as indicated by arrow no. 1. Or did I misunderstand? 
![image](https://user-images.githubusercontent.com/12196246/118952939-a87fa700-b95c-11eb-8cb8-50e53681fe3a.png)

**Comment by Shabirmean** [comment]
Tagging @dinagraves who has more insight into it. 
@dinagraves - can you clarify the above regarding [Time to recover](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/METRICS.md#time-to-restore-services) in METRICS.md?

**Comment by dinagraves** [comment]
Thank you for the great question! 

Ideally, this information would already be correctly categorized in the dimensional incidents table.  Rather than update the query in the metrics calculation, we would assume that the time_created in the `incidents` table is already reflective of the root cause of the incident.   Of course this information is not always available, and at that point we would revert back to the time the incident was detected.  

This [script](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/queries/incidents.sql) would have be updated with the logic.  I will update for the GitHub example we're using.

What are you using for your incident management?

**Comment by dinagraves** [comment]
PR here:  https://github.com/GoogleCloudPlatform/fourkeys/pull/127

**Comment by philipdalen** [comment]
@dinagraves  thanks for the answer. We are using github issues to manage our incidents by labeling them with an label called "incident"

I agree with your approach, if I understand correctly it would mean that if a `root cause:`  commitid has been specified then `time_created` should be the time that commit was released into production, it should be possible to get that from the deployments table. In the case where no ``root cause` was spesified then it should take the time the incident was created. In the below screenshot however you can see that it just always takes the time the incident was created
![image](https://user-images.githubusercontent.com/12196246/119030885-c116ae00-b9aa-11eb-8bb5-c3cf2f447373.png)

**Comment by philipdalen** [comment]
Wow that as fast @dinagraves 🥇
