### ISSUE TITLE
Question: With teams in numerous timezones how do we limit the impact of this on the actual results

### ISSUE THREAD

**Issue by alnutile** [GoogleCloudPlatform/fourkeys#138]
Hello, using your open-source too we created a comparable tool to report on Four Key Metrics. Actually we did not see your opensource tool till after we made this tool inspired of course by the book :)

Anyways, to average out the results we tend to ignore weekends and limit days to 8-12 hours. 

For example we measure our data from GitHub Pull Requests. When was the pull request started, since developers are asked to build the habits of starting it when they are ready to work and working in small batches. But if in many cases a developer might start a PR 3pm their time and closes it 10am the next morning that is still good but might look "bad" if we count the hours they are sleeping or the weekend. When closing the PR and merging to Trunk the numbers would go from 

3-10 am say 4-5 hours to 18+ hours if we do not exclude parts of the day.

Do you have any thoughts on how to do this or is our pattern "good enough".

Thanks

**Comment by dinagraves** [comment]
Hi Alfred!

Great question!  I have a few thoughts.  

Generally, I always say the most important thing is to be consistent!  If your measuring stick is off by 3 inches, you can still use it to measure progress one way or another.   What matters is you keep using the same measuring stick.  

However, trying to correct for these edge cases can start complicating things pretty fast, and it's easy to end up obfuscating the real picture.  Keep in mind that ultimately we care about the end-user experience.  If there is a slower review turn-around due to time-zone differences, that’s good to know.  That’s data!  And that's 18 extra hours before the user gets the new feature.   Maybe the solution is to have at least 2 people in every time zone?  Or maybe when you have all the data, you decide that the bottleneck isn’t the review time at all, and you can push that aside while you tackle the bigger issues.  If you're already in the high performing bucket for this metric (even with the extra time spent eating and sleeping), then you work on something else!   You don’t know unless you have the clear picture with all the data!  

Finally, I would recommend using the median instead of the average -- this data does not have a normal distribution and the median will be a better reflection of a typical performance.  This also means that median is better able to tolerate having some of these higher numbers mixed in.  

It's also important to remember that these are team level metrics and are not meant to be used to measure the performance of individuals -- the developer who starts a PR at 3PM should not be concerned that the turnaround time will be high because of sleeping.  Across the team, this will be just one data point.

I think "active working time" is a good drill-down metric but should probably come 2nd to the top level Lead Time to Change.

**Comment by alnutile** [comment]
ok that makes a lot of sense. Thanks!
