### ISSUE TITLE
generate_data.py --vc_system=github fails to generate fake data

### ISSUE THREAD

**Issue by wpannell** [GoogleCloudPlatform/fourkeys#153]
as a consequence, the data studio report is broken:

**Comment by wpannell** [comment]
![2021-07-06_23-43-17](https://user-images.githubusercontent.com/2018993/124712388-1ef84a00-deb4-11eb-8af3-4bd0cf8b5dce.png)

**Comment by wpannell** [comment]
The `incidents table` fails to load any data.

I'm on the latests revision of the fourkeys repo and the gcloud sdk was updated to the lastest release.

**Comment by dinagraves** [comment]
Thanks for reporting!  Did you run this as part of the setup script or separately? 

The generate_data script should send data through the pipeline to the `events_raw` table.  The scheduled queries, which update the `changes`, `incidents`, and `deployments` tables run every 24 hours.  Have the scheduled queries updated since you ran the generate data script?  

The setup script runs the scheduled queries after the data generation.  If you do it separately, you'll either have to wait for the next run, or you can force it by running the `schedule.sh` in the queries directory.  eg:

`./schedule.sh --query_file=changes.sql --table=changes --project_id=$FOURKEYS_PROJECT`

To make this easier, we're migrating to views so the dashboard will be real-time.  

Please let me know if this did not solve your issue and there is another bug!

**Comment by wpannell** [comment]
> Thanks for reporting! Did you run this as part of the setup script or separately?

Both.

> Have the scheduled queries updated since you ran the generate data script?

Yes.  And, I forced on-demand runs on GCP to check my sanity.  I also repeated the setup process from scratch several times.

> Please let me know if this did not solve your issue and there is another bug! Feel free to reopen!

I originally cloned the repo on `6/4` and I was on  `Google Cloud SDK [342.0.0]`.  I did not see this problem.

I cloned a fresh repo on the date I reported this issue and I upgraded to the latest version of the Google Cloud SDK.

I think this is a real bug that was introduced during that interim.
