### ISSUE TITLE
SQL queries don't work when used in Views

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#155]
There's a branch: `bigquery_views`, which attempts to change from Scheduled Queries to Views (per #130). However, when I try to create those views, I get errors like:

`No matching signature for function JSON_EXTRACT_SCALAR for argument types: INT64, STRING. Supported signature: JSON_EXTRACT_SCALAR(STRING, [STRING]) at [26:10], invalidQuery` (from /queries/deployments.sql)

...we need to modify these queries a bit in order to support Views

**Comment by dinagraves** [comment]
OK so there are some blocking limitations with Materialized Views:  https://cloud.google.com/bigquery/docs/materialized-views#inner_joins 

I did get it to work with an older project with normal views, but I'm a little concerned about the query usage.  https://cloud.google.com/bigquery/docs/views-intro#view_pricing

"BigQuery's views are logical views, not materialized views. Because views are not materialized, the query that defines the view is run each time the view is queried. Queries are billed according to the total amount of data in all table fields referenced directly or indirectly by the top-level query."

WDYT?  

To get it work with the standard views, I changed the temporary function into a permanent function. https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_function_statement

I didn't run into the error you mentioned so I am trying to build a fresh instance to see if there is something different about the current mock data generation.

**Comment by davidstanke** [comment]
Interesting! The cost consideration is certainly worth thinking about. My 2c is that, relative to anyone's production database, we're not talking about all that much data, and the reduction in complexity merits it. Double so when we consider portability--a lot of users would like to deploy to other providers, where BQ specifics won't be available.

So I think we should go for it. 😄

**Comment by dinagraves** [comment]
OK here are the changes.  This needs to be run once: 

```
CREATE FUNCTION four_keys.json2array(json STRING)
RETURNS ARRAY<STRING>
LANGUAGE js AS """
  return JSON.parse(json).map(x=>JSON.stringify(x));
"""; 
```

And then to invoke it in deployments you use `four_keys.json2array(....)`

**Comment by davidstanke** [comment]
FYI for future readers... the issue I had above with `No matching signature for function JSON_EXTRACT_SCALAR for argument types: INT64, STRING` was the result of me having declared the input parameters wrong for the custom function. The queries were fine all along; we just needed to move from a temp function to a permanent one (which is now provisioned via terraform).
