### ISSUE TITLE
No data in Big Query Fourkeys Deployment table 

### ISSUE THREAD

**Issue by Sbhalsing0** [GoogleCloudPlatform/fourkeys#236]
I am using Github as SCM and CloudBuild as CICD. I have integrate Github and Cloudbuild and successfully deploy application on CloudRun but those entry are not populated in BigQuery tables.

![image](https://user-images.githubusercontent.com/42617962/134638775-cab42743-ef57-439d-aead-7ba0ea4ebc3c.png)

Please let me know if I need to change anything.

**Comment by davidstanke** [comment]
Hi @Sbhalsing0 -- let's work backwards one step: do you see data in the `events_raw` table where the `source` field contains "cloudbuild"?

If you do, then something's wrong with the view that generates `deployments`. If you don't, then something's wrong with the ingestion pipeline that populates `events_raw`.

**Comment by Sbhalsing0** [comment]
@davidstanke 

No data in the events_raw table where the source field contains "cloud build".

**Comment by rogerthatdev** [comment]
Hi @Sbhalsing0!
Are you still encountering this issue? It'd be difficult to pinpoint what could be going wrong here. 

My recommendation is that you backup any BigQuery data you might already have and set up Four Keys infrastructure again, as the setup has changed slightly since this issue was opened.  Upon finishing the setup, be sure to use [`generate_data.py`](https://github.com/GoogleCloudPlatform/fourkeys/blob/main/data-generator/generate_data.py) to verify that your event handler and parsers are setup successfully. 

Please re-open this issue if you run into it once again.

Thanks for your patience!
