### ISSUE TITLE
Grafana Dashboard: Non-existent GCE Default Service Account used fetch from BigQuery by default

### ISSUE THREAD

**Issue by jvasallo** [GoogleCloudPlatform/fourkeys#284]
Running through the default setup, the original Grafana Datasource is hardcoded to use GCE Service Account (which is not created by default). 
<img width="1447" alt="Screen Shot 2022-03-25 at 10 33 12 AM" src="https://user-images.githubusercontent.com/1730603/160169465-34910793-027e-4474-949d-3dafda035e49.png">

I ended up needing to create my own JSON Key and manually create a secondary BigQuery Source using that key. Not sure if this is expected :)

**Comment by davidstanke** [comment]
Thanks for the report, @jvasallo! Sounds like we need to explicitly depend on the custom service account (which we are are already creating, so might as well use it here, too).

**Comment by martasd** [comment]
Hi. I cannot see the mock data in Grafana some time after running the script. Is it caused by this issue?

**Comment by rogerthatdev** [comment]
Since the Grafana dashboard does not run from a GCE instance it doesn't actually use the default  GCE service account.  Instead is uses the service account `fourkeys@[PROJECT_ID].iam.gserviceaccount.com` that is created during setup and included on the dashboard Cloud Run service configuration.

Try the following:
- Make sure the Big Query tables contain data.
- Make sure that the `fourkeys` service account has the Big Query User role assigned on the project that includes your BigQuery data.
