### ISSUE TITLE
Big Query connector

### ISSUE THREAD

**Issue by fbtravi** [GoogleCloudPlatform/fourkeys#397]
Hello,

Would it be interesting to change the BigQuery connector, since the one being used in the project is obsolete?

https://doitintl.github.io/bigquery-grafana/

**Comment by davidstanke** [comment]
Hi @fbtravi, yes, that seems like a good idea! Would you be open to implementing it? :)

**Comment by fbtravi** [comment]
Hi @davidstanke.
Yes I would. 
But could you tell me the expected time for a P3? I ask so that I do not delay the progress of the project.

**Comment by davidstanke** [comment]
Great! The current (deprecated) connector is functional, so we don't have a specific timeline for this. We'd of course like to ensure that the project continues to function so we will want to implement the change before the old connector stops working. But since they haven't announced a turndown date, that's not a specified timeframe.

So: it's up to you! We really appreciate your help on Four Keys and will be happy to have the fix when you are able to submit it.

**Comment by fbtravi** [comment]
Cool, I'll do it.
Do I need to assign the issue to me or create a PR to flag my working on this issue?

**Comment by fbtravi** [comment]
Hi,
Send a PR for this, I thought it would take longer to understand how it works xD.
