### ISSUE TITLE
Separate "Elite" from "High" performance in metrics buckets

### ISSUE THREAD

**Issue by davidstanke** [GoogleCloudPlatform/fourkeys#62]
Per the findings in the 2018-2019 [SODR Report](https://cloud.google.com/devops/state-of-devops), there are now four buckets of performers. Accordingly, the [Quick Check tool](https://www.devops-research.com/performance.html?leadtime=1&deployfreq=1&ttr=1&chgfail=6&industry=finance) offers [four buckets](https://www.devops-research.com/performance.html?leadtime=6&deployfreq=6&ttr=6&chgfail=6&industry=finance) when reporting results.

I suggest we use the same rubric, with four buckets for color-coding the dashboard.

**Comment by davidstanke** [comment]
@dinagraves WDYT?

**Comment by michelleirvine** [comment]
Along with this, let's look at how to indicate performance using text as well, so that we're not only relying on colour for the cues (important for accessibility, and also if we update to four buckets, and so have two shades of green for high vs elite, text will help differentiate the two categories).
